# Generated by Django 3.2.20 on 2025-02-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20250216_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position_name',
            field=models.CharField(db_column='positionName', max_length=255),
        ),
    ]
